insert into usuario_entity (email, password, rango) values ('dlangrish0@usach.cl', 'QtqT3G00', 'Ayudante');
insert into usuario_entity (email, password, rango) values ('cferier1@usach.cl', 'i2MWXouYBRN', 'Profesor Titular');
insert into usuario_entity (email, password, rango) values ('bbaggot2@usach.cl', 'KD4Cur', 'Instructor');
insert into usuario_entity (email, password, rango) values ('tmcturlough3@usach.cl', 'XOLM7NBDPZD', 'Profesor Asistente');
insert into usuario_entity (email, password, rango) values ('beloi4@usach.cl', 'AxeGu89ZQaiv', 'Profesor Asistente');
insert into usuario_entity (email, password, rango) values ('lwildblood5@usach.cl', 'XYd9ZuKMx', 'Profesor Titular');
insert into usuario_entity (email, password, rango) values ('fburrass6@usach.cl', '4ZaiffYRFSs8', 'Ayudante');
insert into usuario_entity (email, password, rango) values ('cburril7@usach.cl', 'IZk4fN', 'Profesor Titular');
insert into usuario_entity (email, password, rango) values ('emoncreiff8@usach.cl', 'UG54JupE', 'Ayudante');
insert into usuario_entity (email, password, rango) values ('ddevigne9@usach.cl', 'Nl0iuoYqGcDU', 'Profesor Asistente');
insert into usuario_entity (email, password, rango) values ('sbisha@usach.cl', 'dPmlGfKDqP4q', 'Profesor Asociado');
insert into usuario_entity (email, password, rango) values ('lshanklinb@usach.cl', 'IfFhoXFG7M5', 'Ayudante');
insert into usuario_entity (email, password, rango) values ('bhullinc@usach.cl', 'AF2OucM', 'Profesor Asociado');
insert into usuario_entity (email, password, rango) values ('bmattinsond@usach.cl', 'ddL4wJil', 'Instructor');
insert into usuario_entity (email, password, rango) values ('smeaghere@usach.cl', 'nikBCSJGHpg', 'Instructor');
insert into usuario_entity (email, password, rango) values ('dlethebridgef@usach.cl', 'MsLQL0O1Qul', 'Instructor');
insert into usuario_entity (email, password, rango) values ('clewerenzg@usach.cl', 'ag7GpR1KoD', 'Profesor Asociado');
insert into usuario_entity (email, password, rango) values ('ldartnellh@usach.cl', 'jBEZuqX1D1dd', 'Profesor Asociado');
insert into usuario_entity (email, password, rango) values ('mliasi@usach.cl', 'TRmK9ZVEQ0', 'Instructor');
insert into usuario_entity (email, password, rango) values ('mworsterj@usach.cl', 'aTVY2rx7gB3u', 'Profesor Asistente');
insert into usuario_entity (email, password, rango) values ('rhounsomk@usach.cl', 'onDeKkC38', 'Ayudante');
insert into usuario_entity (email, password, rango) values ('tmaymondl@usach.cl', 'u16nK0qYnbS', 'Profesor Titular');
insert into usuario_entity (email, password, rango) values ('cbeekmanm@usach.cl', 'g9yuAVv9', 'Instructor');
insert into usuario_entity (email, password, rango) values ('croachn@usach.cl', 'xkd6MR', 'Profesor Asociado');
insert into usuario_entity (email, password, rango) values ('chawksleyo@usach.cl', 's285fEX', 'Instructor');
insert into usuario_entity (email, password, rango) values ('rackersp@usach.cl', 'WAe1DD6lsh', 'Profesor Titular');
insert into usuario_entity (email, password, rango) values ('schessumq@usach.cl', '2sSdXSD51P', 'Profesor Asociado');
insert into usuario_entity (email, password, rango) values ('scottrellr@usach.cl', 'F0sugIi7OVA', 'Profesor Asistente');
insert into usuario_entity (email, password, rango) values ('ehembrows@usach.cl', 'IYcbUghhFLw3', 'Profesor Asociado');
insert into usuario_entity (email, password, rango) values ('wveryt@usach.cl', 'h0RMDjoDg3', 'Profesor Asistente');
insert into usuario_entity (email, password, rango) values ('mturnu@usach.cl', 'MEN3Am6', 'Profesor Asociado');
insert into usuario_entity (email, password, rango) values ('nlattav@usach.cl', 'spGqq8pC', 'Profesor Titular');
insert into usuario_entity (email, password, rango) values ('jhounsonw@usach.cl', '7sxnmGfVig', 'Instructor');
insert into usuario_entity (email, password, rango) values ('sduchesnex@usach.cl', 'G3BI1KG7AS', 'Profesor Asistente');
insert into usuario_entity (email, password, rango) values ('sbowray@usach.cl', 'Wovrxti2CIf', 'Profesor Titular');
insert into usuario_entity (email, password, rango) values ('lchengz@usach.cl', 'LWvFhQrDLKi', 'Profesor Titular');
insert into usuario_entity (email, password, rango) values ('thuscroft10@usach.cl', 'hccGtf', 'Instructor');
insert into usuario_entity (email, password, rango) values ('dmcquarter11@usach.cl', 'OQcFnqK', 'Profesor Asociado');
insert into usuario_entity (email, password, rango) values ('jchurchin12@usach.cl', 'NfFv2qzDUJ4', 'Instructor');
insert into usuario_entity (email, password, rango) values ('asporle13@usach.cl', 'iwOAbSYbNE', 'Profesor Asociado');
insert into usuario_entity (email, password, rango) values ('cyurshev14@usach.cl', '3jiD59', 'Profesor Titular');
insert into usuario_entity (email, password, rango) values ('alegerwood15@usach.cl', 'lPjg2uHpap', 'Profesor Titular');
insert into usuario_entity (email, password, rango) values ('ccorns16@usach.cl', 'KLSyLts', 'Instructor');
insert into usuario_entity (email, password, rango) values ('bsabbin17@usach.cl', 'D74jbAJ0Y3v', 'Ayudante');
insert into usuario_entity (email, password, rango) values ('cskully18@usach.cl', 'elviJTLcVk', 'Profesor Titular');
insert into usuario_entity (email, password, rango) values ('mjuleff19@usach.cl', 'P4V5WogdD', 'Instructor');
insert into usuario_entity (email, password, rango) values ('crable1a@usach.cl', 'LS79Af6xK4f', 'Instructor');
insert into usuario_entity (email, password, rango) values ('fpelcheur1b@usach.cl', 'ZbcZIs4y8hyS', 'Ayudante');
insert into usuario_entity (email, password, rango) values ('ccastellino1c@usach.cl', 'M35UwwOgEtCX', 'Profesor Asociado');
insert into usuario_entity (email, password, rango) values ('jdemongeot1d@usach.cl', 'sHHMamxypES', 'Profesor Asociado');